import math
import pytest

from RUFAS.biophysical.animal.ration.calf_ration_manager import (
    MILK_REPLACER_ID,
    STARTER_ID,
    WHOLE_MILK_ID,
    CalfMilkType,
    CalfRationManager,
)
from RUFAS.data_structures.feed_storage_to_animal_connection import (
    NASEMFeed,
    NRCFeed,
    NutrientStandard,
    FeedCategorization,
    FeedComponentType,
)
from RUFAS.units import MeasurementUnits


@pytest.mark.parametrize(
    "milk_type, expected_value",
    [
        (CalfMilkType.WHOLE, "whole"),
        (CalfMilkType.REPLACER, "replacer"),
    ],
)
def test_calf_milk_type(milk_type: CalfMilkType, expected_value: str) -> None:
    assert milk_type.value == expected_value


@pytest.mark.parametrize(
    "milk_type, expected_milk_type",
    [
        (CalfMilkType.WHOLE, CalfMilkType.WHOLE),
        (CalfMilkType.REPLACER, CalfMilkType.REPLACER),
    ],
)
def test_set_milk_type(milk_type: CalfMilkType, expected_milk_type: CalfMilkType) -> None:
    CalfRationManager.set_milk_type(milk_type)

    assert CalfRationManager.milk_type == expected_milk_type


@pytest.mark.parametrize(
    "days_born, body_weight, temp, animal_intake, expected_output",
    [
        # Test case 1: Newborn calf, extreme cold
        (
            10,
            40.0,
            -35.0,
            {
                "whole_milk_intake": 4.0,
                "milk_replacer_intake": 0.0,
                "starter_intake": 0.5,
                "me_intake": 5.0,
                "milk_cp_intake": 0.6,
                "starter_cp_intake": 0.2,
                "cp_intake": 0.8,
                "adp_intake": 0.5,
                "milk_me_proportion": 0.9,
                "starter_me_proportion": 0.1,
                "milk_proportion": 0.8,
                "starter_proportion": 0.2,
            },
            {
                "ne_maint": 3.200805,
                "me_maint": 3.819577,
                "biological_value": 0.77499999,
                "endo_urine_N": 3.18108291,
                "meta_fecal_N": 9.25,
                "adp_maint": 42.438168,
                "me_gain": 1.180422,
                "ne_gain": 0.8003267105,
                "energy_allow_gain": 0.4393775131,
                "adp_allow_gain": -0.172883408,
                "live_weight_change": -0.172883408,
            },
        ),
        # Test case 2: Older calf, mild temperature
        (
            75,
            60.0,
            4.0,
            {
                "whole_milk_intake": 2.0,
                "milk_replacer_intake": 2.0,
                "starter_intake": 1.5,
                "me_intake": 8.0,
                "milk_cp_intake": 0.8,
                "starter_cp_intake": 0.5,
                "cp_intake": 1.3,
                "adp_intake": 0.9,
                "milk_me_proportion": 0.6,
                "starter_me_proportion": 0.4,
                "milk_proportion": 0.5,
                "starter_proportion": 0.5,
            },
            {
                "ne_maint": 2.024207,
                "me_maint": 2.5145431,
                "biological_value": 0.7615384,
                "endo_urine_N": 4.311649,
                "meta_fecal_N": 12.5499999,
                "adp_maint": 59.947248,
                "me_gain": 5.4854568,
                "ne_gain": 3.521663,
                "energy_allow_gain": 1.33901138,
                "adp_allow_gain": -0.23918484,
                "live_weight_change": -0.23918484,
            },
        ),
        # Test case 3: Older calf, very warm temperature
        (
            90,
            75.0,
            -31.0,
            {
                "whole_milk_intake": 1.5,
                "milk_replacer_intake": 2.5,
                "starter_intake": 2.0,
                "me_intake": 9.0,
                "milk_cp_intake": 1.0,
                "starter_cp_intake": 0.7,
                "cp_intake": 1.7,
                "adp_intake": 1.1,
                "milk_me_proportion": 0.5,
                "starter_me_proportion": 0.5,
                "milk_proportion": 0.4,
                "starter_proportion": 0.6,
            },
            {
                "ne_maint": 4.5369578,
                "me_maint": 5.7140527,
                "biological_value": 0.75882352,
                "endo_urine_N": 5.097132,
                "meta_fecal_N": 14.2,
                "adp_maint": 70.189562,
                "me_gain": 3.28594729,
                "ne_gain": 2.070146796,
                "energy_allow_gain": 0.8052199692,
                "adp_allow_gain": -0.27886588,
                "live_weight_change": -0.27886588,
            },
        ),
        # Test case 4: Newborn calf, mild temperature
        (
            10,
            40.0,
            10.0,
            {
                "whole_milk_intake": 4.0,
                "milk_replacer_intake": 0.0,
                "starter_intake": 0.5,
                "me_intake": 5.0,
                "milk_cp_intake": 0.6,
                "starter_cp_intake": 0.2,
                "cp_intake": 0.8,
                "adp_intake": 0.5,
                "milk_me_proportion": 0.9,
                "starter_me_proportion": 0.1,
                "milk_proportion": 0.8,
                "starter_proportion": 0.2,
            },
            {
                "ne_maint": 1.64567916,
                "me_maint": 1.96381762,
                "biological_value": 0.77499999,
                "endo_urine_N": 3.18108291,
                "meta_fecal_N": 9.25,
                "adp_maint": 42.438168,
                "me_gain": 3.03618237744,
                "ne_gain": 2.058531651,
                "energy_allow_gain": 0.965182845,
                "adp_allow_gain": -0.172883408,
                "live_weight_change": -0.172883408,
            },
        ),
    ],
)
def test_calc_requirements(
    days_born: int,
    body_weight: float,
    temp: float,
    animal_intake: dict[str, int | float],
    expected_output: dict[str, float],
) -> None:
    result = CalfRationManager.calc_requirements(days_born, body_weight, temp, animal_intake)

    for key, expected_value in expected_output.items():
        assert math.isclose(result[key], expected_value, rel_tol=1e-6)


@pytest.mark.parametrize(
    "birth_weight, body_weight, wean_day, wean_length, available_feeds, nutrient_standard, expected_output",
    [
        (
            40.0,
            45.0,
            60,
            14,
            [
                NASEMFeed(
                    rufas_id=WHOLE_MILK_ID,
                    Name="Whole Milk",
                    Fd_Category="Liquid",
                    feed_type="Milk",
                    DM=12.5,
                    ash=0.0,
                    CP=27.0,
                    N_A=0.0,
                    N_B=0.0,
                    N_C=0.0,
                    Kd=0.0,
                    dRUP=0.0,
                    ADICP=0.0,
                    NDICP=0.0,
                    ADF=0.0,
                    NDF=0.0,
                    lignin=0.0,
                    starch=0.0,
                    EE=0.0,
                    calcium=0.0,
                    phosphorus=0.0,
                    magnesium=0.0,
                    potassium=0.0,
                    sodium=0.0,
                    chlorine=0.0,
                    sulfur=0.0,
                    is_fat=False,
                    is_wetforage=False,
                    units="kg",
                    limit=999.0,
                    lower_limit=0.0,
                    TDN=0.0,
                    DE=5.5,
                    amount_available=999.0,
                    on_farm_cost=0.0,
                    purchase_cost=0.0,
                    RUP=0.0,
                    sol_prot=0.0,
                    NDF48=0.0,
                    WSC=0.0,
                    FA=0.0,
                    DE_Base=5.5,
                    copper=0.0,
                    iron=0.0,
                    manganese=0.0,
                    zinc=0.0,
                    molibdenum=0.0,
                    chromium=0.0,
                    cobalt=0.0,
                    iodine=0.0,
                    selenium=0.0,
                    arginine=0.0,
                    histidine=0.0,
                    isoleucine=0.0,
                    leucine=0.0,
                    lysine=0.0,
                    methionine=0.0,
                    phenylalanine=0.0,
                    threonine=0.0,
                    triptophan=0.0,
                    valine=0.0,
                    C120_FA=0.0,
                    C140_FA=0.0,
                    C160_FA=0.0,
                    C161_FA=0.0,
                    C180_FA=0.0,
                    C181t_FA=0.0,
                    C181c_FA=0.0,
                    C182_FA=0.0,
                    C183_FA=0.0,
                    otherFA_FA=0.0,
                    NPN_source=0.0,
                    starch_digested=0.0,
                    FA_dig=0.0,
                    P_inorg=0.0,
                    P_org=0.0,
                    B_Carotene=0.0,
                    biotin=0.0,
                    choline=0.0,
                    niacin=0.0,
                    Vit_A=0.0,
                    Vit_D=0.0,
                    Vit_E=0.0,
                    Abs_calcium=0.0,
                    Abs_phosphorus=0.0,
                    Abs_sodium=0.0,
                    Abs_chloride=0.0,
                    Abs_potassium=0.0,
                    Abs_copper=0.0,
                    Abs_iron=0.0,
                    Abs_magnesium=0.0,
                    Abs_manganesum=0.0,
                    Abs_zinc=0.0,
                    buffer=0.0,
                ),
                NASEMFeed(
                    rufas_id=MILK_REPLACER_ID,
                    Name="Milk Replacer",
                    Fd_Category="Liquid",
                    feed_type="Milk",
                    DM=13.2,
                    ash=0.0,
                    CP=25.0,
                    N_A=0.0,
                    N_B=0.0,
                    N_C=0.0,
                    Kd=0.0,
                    dRUP=0.0,
                    ADICP=0.0,
                    NDICP=0.0,
                    ADF=0.0,
                    NDF=0.0,
                    lignin=0.0,
                    starch=0.0,
                    EE=0.0,
                    calcium=0.0,
                    phosphorus=0.0,
                    magnesium=0.0,
                    potassium=0.0,
                    sodium=0.0,
                    chlorine=0.0,
                    sulfur=0.0,
                    is_fat=False,
                    is_wetforage=False,
                    units="kg",
                    limit=999.0,
                    lower_limit=0.0,
                    TDN=0.0,
                    DE=5.3,
                    amount_available=999.0,
                    on_farm_cost=0.0,
                    purchase_cost=0.0,
                    RUP=0.0,
                    sol_prot=0.0,
                    NDF48=0.0,
                    WSC=0.0,
                    FA=0.0,
                    DE_Base=5.3,
                    copper=0.0,
                    iron=0.0,
                    manganese=0.0,
                    zinc=0.0,
                    molibdenum=0.0,
                    chromium=0.0,
                    cobalt=0.0,
                    iodine=0.0,
                    selenium=0.0,
                    arginine=0.0,
                    histidine=0.0,
                    isoleucine=0.0,
                    leucine=0.0,
                    lysine=0.0,
                    methionine=0.0,
                    phenylalanine=0.0,
                    threonine=0.0,
                    triptophan=0.0,
                    valine=0.0,
                    C120_FA=0.0,
                    C140_FA=0.0,
                    C160_FA=0.0,
                    C161_FA=0.0,
                    C180_FA=0.0,
                    C181t_FA=0.0,
                    C181c_FA=0.0,
                    C182_FA=0.0,
                    C183_FA=0.0,
                    otherFA_FA=0.0,
                    NPN_source=0.0,
                    starch_digested=0.0,
                    FA_dig=0.0,
                    P_inorg=0.0,
                    P_org=0.0,
                    B_Carotene=0.0,
                    biotin=0.0,
                    choline=0.0,
                    niacin=0.0,
                    Vit_A=0.0,
                    Vit_D=0.0,
                    Vit_E=0.0,
                    Abs_calcium=0.0,
                    Abs_phosphorus=0.0,
                    Abs_sodium=0.0,
                    Abs_chloride=0.0,
                    Abs_potassium=0.0,
                    Abs_copper=0.0,
                    Abs_iron=0.0,
                    Abs_magnesium=0.0,
                    Abs_manganesum=0.0,
                    Abs_zinc=0.0,
                    buffer=0.0,
                ),
                NASEMFeed(
                    rufas_id=STARTER_ID,
                    Name="Starter Feed",
                    Fd_Category="Solid",
                    feed_type="Starter",
                    DM=88.0,
                    ash=0.0,
                    CP=20.0,
                    N_A=0.0,
                    N_B=0.0,
                    N_C=0.0,
                    Kd=0.0,
                    dRUP=0.0,
                    ADICP=0.0,
                    NDICP=0.0,
                    ADF=0.0,
                    NDF=0.0,
                    lignin=0.0,
                    starch=0.0,
                    EE=0.0,
                    calcium=0.0,
                    phosphorus=0.0,
                    magnesium=0.0,
                    potassium=0.0,
                    sodium=0.0,
                    chlorine=0.0,
                    sulfur=0.0,
                    is_fat=False,
                    is_wetforage=False,
                    units="kg",
                    limit=999.0,
                    lower_limit=0.0,
                    TDN=0.0,
                    DE=4.5,
                    amount_available=999.0,
                    on_farm_cost=0.0,
                    purchase_cost=0.0,
                    RUP=0.0,
                    sol_prot=0.0,
                    NDF48=0.0,
                    WSC=0.0,
                    FA=0.0,
                    DE_Base=4.5,
                    copper=0.0,
                    iron=0.0,
                    manganese=0.0,
                    zinc=0.0,
                    molibdenum=0.0,
                    chromium=0.0,
                    cobalt=0.0,
                    iodine=0.0,
                    selenium=0.0,
                    arginine=0.0,
                    histidine=0.0,
                    isoleucine=0.0,
                    leucine=0.0,
                    lysine=0.0,
                    methionine=0.0,
                    phenylalanine=0.0,
                    threonine=0.0,
                    triptophan=0.0,
                    valine=0.0,
                    C120_FA=0.0,
                    C140_FA=0.0,
                    C160_FA=0.0,
                    C161_FA=0.0,
                    C180_FA=0.0,
                    C181t_FA=0.0,
                    C181c_FA=0.0,
                    C182_FA=0.0,
                    C183_FA=0.0,
                    otherFA_FA=0.0,
                    NPN_source=0.0,
                    starch_digested=0.0,
                    FA_dig=0.0,
                    P_inorg=0.0,
                    P_org=0.0,
                    B_Carotene=0.0,
                    biotin=0.0,
                    choline=0.0,
                    niacin=0.0,
                    Vit_A=0.0,
                    Vit_D=0.0,
                    Vit_E=0.0,
                    Abs_calcium=0.0,
                    Abs_phosphorus=0.0,
                    Abs_sodium=0.0,
                    Abs_chloride=0.0,
                    Abs_potassium=0.0,
                    Abs_copper=0.0,
                    Abs_iron=0.0,
                    Abs_magnesium=0.0,
                    Abs_manganesum=0.0,
                    Abs_zinc=0.0,
                    buffer=0.0,
                ),
            ],
            NutrientStandard.NASEM,
            {
                "whole_milk_intake": 0.5,
                "milk_replacer_intake": 0.0,
                "starter_intake": 0.01,
                "wean_start": 45,
                "milk_reduction": 7,
                "milk_intake_wean": 0.26666666,
                "dry_matter_intake": 0.51,
                "me_intake": 2.681018999,
                "milk_cp_intake": 0.135,
                "starter_cp_intake": 0.002,
                "cp_intake": 0.137,
                "adp_intake": 927.372262,
                "milk_me_proportion": 0.9847002,
                "starter_me_proportion": 0.0152997796,
                "milk_proportion": 0.9803921,
                "starter_proportion": 0.01960784,
            },
        ),
    ],
)
def test_calc_intake(
    birth_weight: float,
    body_weight: float,
    wean_day: int,
    wean_length: int,
    available_feeds: list[NASEMFeed | NRCFeed],
    nutrient_standard: NutrientStandard,
    expected_output: dict[str, float],
) -> None:
    CalfRationManager.milk_type = (
        CalfMilkType.WHOLE if expected_output["whole_milk_intake"] > 0 else CalfMilkType.REPLACER
    )

    result = CalfRationManager.calc_intake(
        birth_weight, body_weight, wean_day, wean_length, available_feeds, nutrient_standard
    )

    for key, expected_value in expected_output.items():
        assert math.isclose(result[key], expected_value, rel_tol=1e-6)


@pytest.fixture
def whole_milk() -> NASEMFeed:
    return NASEMFeed(
        rufas_id=WHOLE_MILK_ID,
        Name="Whole Milk",
        Fd_Category=FeedCategorization.CALF_LIQUID_FEED,
        feed_type=FeedComponentType.MILK,
        DM=12.5,
        ash=0.0,
        CP=27.0,
        N_A=0.0,
        N_B=0.0,
        N_C=0.0,
        Kd=0.0,
        dRUP=0.0,
        ADICP=0.0,
        NDICP=0.0,
        ADF=0.0,
        NDF=0.0,
        lignin=0.0,
        starch=0.0,
        EE=0.0,
        calcium=0.0,
        phosphorus=0.0,
        magnesium=0.0,
        potassium=0.0,
        sodium=0.0,
        chlorine=0.0,
        sulfur=0.0,
        is_fat=False,
        is_wetforage=False,
        units=MeasurementUnits.KILOGRAMS,
        limit=999.0,
        lower_limit=0.0,
        TDN=0.0,
        DE=5.5,
        amount_available=999.0,
        on_farm_cost=0.0,
        purchase_cost=0.0,
        RUP=0.0,
        sol_prot=0.0,
        NDF48=0.0,
        WSC=0.0,
        FA=0.0,
        DE_Base=5.5,
        copper=0.0,
        iron=0.0,
        manganese=0.0,
        zinc=0.0,
        molibdenum=0.0,
        chromium=0.0,
        cobalt=0.0,
        iodine=0.0,
        selenium=0.0,
        arginine=0.0,
        histidine=0.0,
        isoleucine=0.0,
        leucine=0.0,
        lysine=0.0,
        methionine=0.0,
        phenylalanine=0.0,
        threonine=0.0,
        triptophan=0.0,
        valine=0.0,
        C120_FA=0.0,
        C140_FA=0.0,
        C160_FA=0.0,
        C161_FA=0.0,
        C180_FA=0.0,
        C181t_FA=0.0,
        C181c_FA=0.0,
        C182_FA=0.0,
        C183_FA=0.0,
        otherFA_FA=0.0,
        NPN_source=0.0,
        starch_digested=0.0,
        FA_dig=0.0,
        P_inorg=0.0,
        P_org=0.0,
        B_Carotene=0.0,
        biotin=0.0,
        choline=0.0,
        niacin=0.0,
        Vit_A=0.0,
        Vit_D=0.0,
        Vit_E=0.0,
        Abs_calcium=0.0,
        Abs_phosphorus=0.0,
        Abs_sodium=0.0,
        Abs_chloride=0.0,
        Abs_potassium=0.0,
        Abs_copper=0.0,
        Abs_iron=0.0,
        Abs_magnesium=0.0,
        Abs_manganesum=0.0,
        Abs_zinc=0.0,
        buffer=0.0,
    )


@pytest.fixture
def milk_replacer() -> NASEMFeed:
    return NASEMFeed(
        rufas_id=MILK_REPLACER_ID,
        Name="Milk Replacer",
        Fd_Category=FeedCategorization.CALF_LIQUID_FEED,
        feed_type=FeedComponentType.MILK,
        DM=13.2,
        ash=0.0,
        CP=25.0,
        N_A=0.0,
        N_B=0.0,
        N_C=0.0,
        Kd=0.0,
        dRUP=0.0,
        ADICP=0.0,
        NDICP=0.0,
        ADF=0.0,
        NDF=0.0,
        lignin=0.0,
        starch=0.0,
        EE=0.0,
        calcium=0.0,
        phosphorus=0.0,
        magnesium=0.0,
        potassium=0.0,
        sodium=0.0,
        chlorine=0.0,
        sulfur=0.0,
        is_fat=False,
        is_wetforage=False,
        units=MeasurementUnits.KILOGRAMS,
        limit=999.0,
        lower_limit=0.0,
        TDN=0.0,
        DE=5.3,
        amount_available=999.0,
        on_farm_cost=0.0,
        purchase_cost=0.0,
        RUP=0.0,
        sol_prot=0.0,
        NDF48=0.0,
        WSC=0.0,
        FA=0.0,
        DE_Base=5.3,
        copper=0.0,
        iron=0.0,
        manganese=0.0,
        zinc=0.0,
        molibdenum=0.0,
        chromium=0.0,
        cobalt=0.0,
        iodine=0.0,
        selenium=0.0,
        arginine=0.0,
        histidine=0.0,
        isoleucine=0.0,
        leucine=0.0,
        lysine=0.0,
        methionine=0.0,
        phenylalanine=0.0,
        threonine=0.0,
        triptophan=0.0,
        valine=0.0,
        C120_FA=0.0,
        C140_FA=0.0,
        C160_FA=0.0,
        C161_FA=0.0,
        C180_FA=0.0,
        C181t_FA=0.0,
        C181c_FA=0.0,
        C182_FA=0.0,
        C183_FA=0.0,
        otherFA_FA=0.0,
        NPN_source=0.0,
        starch_digested=0.0,
        FA_dig=0.0,
        P_inorg=0.0,
        P_org=0.0,
        B_Carotene=0.0,
        biotin=0.0,
        choline=0.0,
        niacin=0.0,
        Vit_A=0.0,
        Vit_D=0.0,
        Vit_E=0.0,
        Abs_calcium=0.0,
        Abs_phosphorus=0.0,
        Abs_sodium=0.0,
        Abs_chloride=0.0,
        Abs_potassium=0.0,
        Abs_copper=0.0,
        Abs_iron=0.0,
        Abs_magnesium=0.0,
        Abs_manganesum=0.0,
        Abs_zinc=0.0,
        buffer=0.0,
    )


@pytest.fixture
def starter() -> NASEMFeed:
    return NASEMFeed(
        rufas_id=STARTER_ID,
        Name="Starter Feed",
        Fd_Category=FeedCategorization.GRAIN_CROP_FORAGE,
        feed_type=FeedComponentType.STARTER,
        DM=88.0,
        ash=0.0,
        CP=20.0,
        N_A=0.0,
        N_B=0.0,
        N_C=0.0,
        Kd=0.0,
        dRUP=0.0,
        ADICP=0.0,
        NDICP=0.0,
        ADF=0.0,
        NDF=0.0,
        lignin=0.0,
        starch=0.0,
        EE=0.0,
        calcium=0.0,
        phosphorus=0.0,
        magnesium=0.0,
        potassium=0.0,
        sodium=0.0,
        chlorine=0.0,
        sulfur=0.0,
        is_fat=False,
        is_wetforage=False,
        units=MeasurementUnits.KILOGRAMS,
        limit=999.0,
        lower_limit=0.0,
        TDN=0.0,
        DE=4.5,
        amount_available=999.0,
        on_farm_cost=0.0,
        purchase_cost=0.0,
        RUP=0.0,
        sol_prot=0.0,
        NDF48=0.0,
        WSC=0.0,
        FA=0.0,
        DE_Base=4.5,
        copper=0.0,
        iron=0.0,
        manganese=0.0,
        zinc=0.0,
        molibdenum=0.0,
        chromium=0.0,
        cobalt=0.0,
        iodine=0.0,
        selenium=0.0,
        arginine=0.0,
        histidine=0.0,
        isoleucine=0.0,
        leucine=0.0,
        lysine=0.0,
        methionine=0.0,
        phenylalanine=0.0,
        threonine=0.0,
        triptophan=0.0,
        valine=0.0,
        C120_FA=0.0,
        C140_FA=0.0,
        C160_FA=0.0,
        C161_FA=0.0,
        C180_FA=0.0,
        C181t_FA=0.0,
        C181c_FA=0.0,
        C182_FA=0.0,
        C183_FA=0.0,
        otherFA_FA=0.0,
        NPN_source=0.0,
        starch_digested=0.0,
        FA_dig=0.0,
        P_inorg=0.0,
        P_org=0.0,
        B_Carotene=0.0,
        biotin=0.0,
        choline=0.0,
        niacin=0.0,
        Vit_A=0.0,
        Vit_D=0.0,
        Vit_E=0.0,
        Abs_calcium=0.0,
        Abs_phosphorus=0.0,
        Abs_sodium=0.0,
        Abs_chloride=0.0,
        Abs_potassium=0.0,
        Abs_copper=0.0,
        Abs_iron=0.0,
        Abs_magnesium=0.0,
        Abs_manganesum=0.0,
        Abs_zinc=0.0,
        buffer=0.0,
    )


@pytest.mark.parametrize(
    "birth_weight, body_weight, wean_day, wean_length, available_feeds, nutrient_standard, expected_output",
    [
        # Test Case 1: Calf on Whole Milk (Existing Case)
        (
            40.0,
            45.0,
            60,
            14,
            ["whole_milk", "milk_replacer", "starter"],
            NutrientStandard.NASEM,
            {
                "whole_milk_intake": 0.5,
                "milk_replacer_intake": 0.0,
                "starter_intake": 0.01,
                "wean_start": 45,
                "milk_reduction": 7,
                "milk_intake_wean": 0.266666666,
                "dry_matter_intake": 0.51,
                "me_intake": 2.68101899,
                "milk_cp_intake": 0.135,
                "starter_cp_intake": 0.002,
                "cp_intake": 0.137,
                "adp_intake": 927.372262,
                "milk_me_proportion": 0.98470022,
                "starter_me_proportion": 0.01529977,
                "milk_proportion": 0.98039215,
                "starter_proportion": 0.019607843,
            },
        ),
        # Test Case 2: Calf on Milk Replacer, Covers 'else' branch where whole_milk_intake = 0.0
        (
            45.0,
            50.0,
            70,
            21,
            ["whole_milk", "milk_replacer", "starter"],
            NutrientStandard.NRC,
            {
                "whole_milk_intake": 0.0,
                "milk_replacer_intake": 0.594,
                "starter_intake": 0.01,
                "wean_start": 48,
                "milk_reduction": 10,
                "milk_intake_wean": 0.323999999,
                "dry_matter_intake": 0.604,
                "me_intake": 3.063291,
                "milk_cp_intake": 0.1485,
                "starter_cp_intake": 0.002,
                "cp_intake": 0.1505,
                "adp_intake": 927.6079734,
                "milk_me_proportion": 0.986609499,
                "starter_me_proportion": 0.0133905006,
                "milk_proportion": 0.983443708,
                "starter_proportion": 0.01655629,
            },
        ),
        # Test Case 3: Covers 'else' where 'starter_digestible_energy = starter.DE'
        (
            50.0,
            60.0,
            80,
            20,
            ["whole_milk", "milk_replacer", "starter"],
            NutrientStandard.NRC,
            {
                "whole_milk_intake": 0.0,
                "milk_replacer_intake": 0.66,
                "starter_intake": 0.0495720,  # Covers 50.0 < body_weight <= 69.365
                "wean_start": 59,
                "milk_reduction": 10,
                "milk_intake_wean": 0.3457142,
                "dry_matter_intake": 0.7095720,
                "me_intake": 3.56141938,
                "milk_cp_intake": 0.165,
                "starter_cp_intake": 0.00991440,
                "cp_intake": 0.1749144,
                "adp_intake": 919.7973408,
                "milk_me_proportion": 0.94290495,
                "starter_me_proportion": 0.057095041,
                "milk_proportion": 0.93013816,
                "starter_proportion": 0.06986183,
            },
        ),
        # Test Case 4: Covers 'else' where body_weight > 69.365 for 'starter_intake'
        (
            55.0,
            70.5,
            90,
            28,
            ["whole_milk", "milk_replacer", "starter"],
            NutrientStandard.NASEM,
            {
                "whole_milk_intake": 0.0,
                "milk_replacer_intake": 0.726,
                "starter_intake": 0.1994224,
                "wean_start": 61,
                "milk_reduction": 14,
                "milk_intake_wean": 0.37551724,
                "dry_matter_intake": 0.9254224,
                "me_intake": 4.5118991,
                "milk_cp_intake": 0.1815,
                "starter_cp_intake": 0.0398844999,
                "cp_intake": 0.2213844999,
                "adp_intake": 897.571306,
                "milk_me_proportion": 0.8186991,
                "starter_me_proportion": 0.1813008502,
                "milk_proportion": 0.78450653,
                "starter_proportion": 0.2154934637,
            },
        ),
    ],
)
def test_calc_intake_2(
    birth_weight: float,
    body_weight: float,
    wean_day: int,
    wean_length: int,
    available_feeds: list[str],
    nutrient_standard: NutrientStandard,
    expected_output: dict[str, float],
    whole_milk: NASEMFeed,
    milk_replacer: NASEMFeed,
    starter: NASEMFeed,
) -> None:
    # Select the correct milk type based on the test case
    CalfRationManager.milk_type = (
        CalfMilkType.WHOLE if expected_output["whole_milk_intake"] > 0 else CalfMilkType.REPLACER
    )

    # Resolve fixture references into actual objects
    feed_objects = {"whole_milk": whole_milk, "milk_replacer": milk_replacer, "starter": starter}
    selected_feeds: list[NASEMFeed | NRCFeed] = [feed_objects[feed] for feed in available_feeds]

    # Run the function under test
    result = CalfRationManager.calc_intake(
        birth_weight, body_weight, wean_day, wean_length, selected_feeds, nutrient_standard
    )

    # Validate results
    for key, expected_value in expected_output.items():
        assert math.isclose(result[key], expected_value, rel_tol=1e-6), f"Mismatch in {key}"
