from typing import Any
from unittest.mock import MagicMock

import pytest
from pytest_mock import MockerFixture

from RUFAS.biophysical.manure.manure_manager import ManureManager
from RUFAS.biophysical.manure.manure_nutrient_manager import ManureNutrientManager
from RUFAS.data_structures.manure_nutrients import ManureNutrients
from RUFAS.data_structures.manure_types import ManureType
from RUFAS.output_manager import OutputManager


@pytest.fixture
def manure_management_input_json() -> dict[str, list[dict[str, Any]]]:
    return {
        "anaerobic_digester": [
            {
                "name": "anaerobic_digester_1",
                "processor_type": "ContinuousMix",
                "hydraulic_retention_time": 25,
                "top_cover_volume_fraction": 0.2,
                "evaporation_fraction": 0.02,
                "temperature_set_point": 37.5,
                "methane_leakage_fraction": 0.01,
            },
            {
                "name": "anaerobic_digester_2",
                "processor_type": "ContinuousMix",
                "hydraulic_retention_time": 25,
                "top_cover_volume_fraction": 0.2,
                "evaporation_fraction": 0.02,
                "temperature_set_point": 37.5,
                "methane_leakage_fraction": 0.01,
            },
        ],
        "handler": [
            {
                "name": "alley_scraper_1",
                "processor_type": "AlleyScraper",
                "handler_type": "AlleyScraper",
                "cleaning_water_use_amount": 0.0,
                "cleaning_water_recycle_fraction": 0.8,
                "use_parlor_flush": False,
            },
            {
                "name": "manual_scraper_1",
                "processor_type": "ManualScraper",
                "handler_type": "ManualScraper",
                "cleaning_water_use_amount": 0.0,
                "cleaning_water_recycle_fraction": 0.8,
                "use_parlor_flush": False,
            },
            {
                "name": "flush_system_1",
                "processor_type": "FlushSystem",
                "handler_type": "FlushSystem",
                "cleaning_water_use_amount": 0.0,
                "cleaning_water_recycle_fraction": 0.8,
                "use_parlor_flush": False,
            },
            {
                "name": "parlor_cleaning_handler_1",
                "processor_type": "ParlorCleaningHandler",
                "handler_type": "ParlorCleaningHandler",
                "cleaning_water_use_amount": 0.0,
                "cleaning_water_recycle_fraction": 0.8,
                "use_parlor_flush": True,
            },
        ],
        "separator": [
            {
                "name": "rotary_screen_1",
                "processor_type": "RotaryScreen",
                "separated_solids_dry_matter": 0.20,
                "total_solids_efficiency": 0.35,
                "volatile_solids_efficiency": 0.40,
                "nitrogen_efficiency": 0.30,
                "ammoniacal_nitrogen_efficiency": 0.15,
                "phosphorus_efficiency": 0.40,
                "potassium_efficiency": 0.15,
                "ash_efficiency": 0.20,
            },
            {
                "name": "screw_press_1",
                "processor_type": "ScrewPress",
                "separated_solids_dry_matter": 0.35,
                "total_solids_efficiency": 0.25,
                "volatile_solids_efficiency": 0.30,
                "nitrogen_efficiency": 0.30,
                "ammoniacal_nitrogen_efficiency": 0.10,
                "phosphorus_efficiency": 0.20,
                "potassium_efficiency": 0.23,
                "ash_efficiency": 0.20,
            },
        ],
        "storage": [
            {
                "name": "slurry_storage_outdoor_1",
                "processor_type": "SlurryStorageOutdoor",
                "capacity": None,
                "cover": "no cover",
                "storage_time_period": 120,
                "surface_area": None,
            },
            {
                "name": "slurry_storage_underfloor_1",
                "processor_type": "SlurryStorageUnderfloor",
                "capacity": None,
                "cover": "cover",
                "storage_time_period": 120,
                "surface_area": None,
            },
            {
                "name": "anaerobic_lagoon_1",
                "processor_type": "AnaerobicLagoon",
                "capacity": None,
                "cover": "no cover",
                "storage_time_period": 365,
                "surface_area": None,
            },
        ],
    }


@pytest.fixture
def processor_connections_input_json() -> dict[str, list[dict[str, Any]]]:
    return {
        "processor_connections": [
            {
                "processor_name": "alley_scraper_1",
                "destinations": [
                    {"receiving_processor_name": "rotary_screen_1", "proportion": 0.5},
                    {"receiving_processor_name": "anaerobic_digester_1", "proportion": 0.5},
                ],
            },
            {
                "processor_name": "flush_system_1",
                "destinations": [
                    {"receiving_processor_name": "screw_press_1", "proportion": 0.1},
                    {"receiving_processor_name": "parlor_cleaning_handler_1", "proportion": 0.8},
                    {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.1},
                ],
            },
            {
                "processor_name": "parlor_cleaning_handler_1",
                "destinations": [
                    {"receiving_processor_name": "anaerobic_digester_2", "proportion": 0.18},
                    {"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 0.68},
                    {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.14},
                ],
            },
            {
                "processor_name": "anaerobic_digester_1",
                "destinations": [
                    {"receiving_processor_name": "flush_system_1", "proportion": 0.93},
                    {"receiving_processor_name": "screw_press_1", "proportion": 0.07},
                ],
            },
            {
                "processor_name": "anaerobic_digester_2",
                "destinations": [{"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 1.0}],
            },
            {"processor_name": "anaerobic_lagoon_1", "destinations": []},
            {"processor_name": "slurry_storage_outdoor_1", "destinations": []},
        ],
        "separator_connections": [
            {
                "processor_name": "rotary_screen_1",
                "liquid_output_destinations": [{"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 1.0}],
                "solid_output_destinations": [
                    {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 1.0}
                ],
            },
            {
                "processor_name": "screw_press_1",
                "liquid_output_destinations": [{"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 1.0}],
                "solid_output_destinations": [
                    {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.2},
                    {"receiving_processor_name": "anaerobic_digester_2", "proportion": 0.8},
                ],
            },
        ],
    }


@pytest.fixture
def manure_manager(mocker: MockerFixture) -> ManureManager:
    mocker.patch("RUFAS.biophysical.manure.manure_manager.ManureManager.__init__", return_value=None)
    manure_manager = ManureManager(0.5, 0.5, 0.5)
    mnm = ManureNutrientManager()
    mnm.add_nutrients(
        ManureNutrients(
            manure_type=ManureType.LIQUID,
            nitrogen=100,
            phosphorus=200,
        )
    )
    manure_manager._manure_nutrient_manager = mnm
    manure_manager.all_processors, manure_manager._all_separators, manure_manager._adjacency_matrix = {}, {}, {}
    manure_manager._processing_order = []
    manure_manager._om = MagicMock(auto_spec=OutputManager)

    return manure_manager


@pytest.fixture
def expected_all_processor_names_in_connection_map() -> list[str]:
    return [
        "alley_scraper_1",
        "flush_system_1",
        "parlor_cleaning_handler_1",
        "anaerobic_digester_1",
        "anaerobic_digester_2",
        "anaerobic_lagoon_1",
        "slurry_storage_outdoor_1",
        "rotary_screen_1",
        "screw_press_1",
    ]


@pytest.fixture
def expected_all_defined_processor_names() -> list[str]:
    return [
        "anaerobic_digester_1",
        "anaerobic_digester_2",
        "rotary_screen_1",
        "screw_press_1",
        "slurry_storage_outdoor_1",
        "slurry_storage_underfloor_1",
        "anaerobic_lagoon_1",
        "alley_scraper_1",
        "manual_scraper_1",
        "flush_system_1",
        "parlor_cleaning_handler_1",
    ]


@pytest.fixture
def expected_all_separator_names() -> list[str]:
    return ["rotary_screen_1", "screw_press_1"]


@pytest.fixture
def expected_adjacency_matrix_after_merge() -> dict[str, dict[str, float]]:
    return {
        "alley_scraper_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.5,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1": 0.5,
            "screw_press_1": 0.0,
        },
        "flush_system_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.8,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.1,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.1,
        },
        "parlor_cleaning_handler_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.18,
            "anaerobic_lagoon_1": 0.68,
            "slurry_storage_outdoor_1": 0.14,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
        "anaerobic_digester_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.93,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.07,
        },
        "anaerobic_digester_2": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
        "anaerobic_lagoon_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
        "slurry_storage_outdoor_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
        "rotary_screen_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
        "screw_press_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.8,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 0.2,
            "rotary_screen_1": 0.0,
            "screw_press_1": 0.0,
        },
    }


@pytest.fixture
def invalid_separator_adjacency_matrix() -> dict[str, dict[str, float]]:
    return {
        "alley_scraper_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.5,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.5,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "flush_system_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.8,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.1,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.1,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "parlor_cleaning_handler_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.18,
            "anaerobic_lagoon_1": 0.68,
            "slurry_storage_outdoor_1": 0.14,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.93,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.07,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_2": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_lagoon_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "slurry_storage_outdoor_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.8,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.2,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
    }


@pytest.fixture
def expected_adjacency_matrix() -> dict[str, dict[str, float]]:
    return {
        "alley_scraper_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.5,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.5,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "flush_system_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.8,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.1,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.1,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "parlor_cleaning_handler_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.18,
            "anaerobic_lagoon_1": 0.68,
            "slurry_storage_outdoor_1": 0.14,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.93,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.07,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_2": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_lagoon_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "slurry_storage_outdoor_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 1.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.8,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.2,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 1.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
    }


@pytest.fixture
def expected_empty_adjacency_matrix() -> dict[str, dict[str, float]]:
    return {
        "alley_scraper_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "flush_system_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "parlor_cleaning_handler_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_digester_2": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "anaerobic_lagoon_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "slurry_storage_outdoor_1": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "rotary_screen_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_input": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_solid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
        "screw_press_1_liquid_output": {
            "alley_scraper_1": 0.0,
            "flush_system_1": 0.0,
            "parlor_cleaning_handler_1": 0.0,
            "anaerobic_digester_1": 0.0,
            "anaerobic_digester_2": 0.0,
            "anaerobic_lagoon_1": 0.0,
            "slurry_storage_outdoor_1": 0.0,
            "rotary_screen_1_input": 0.0,
            "rotary_screen_1_solid_output": 0.0,
            "rotary_screen_1_liquid_output": 0.0,
            "screw_press_1_input": 0.0,
            "screw_press_1_solid_output": 0.0,
            "screw_press_1_liquid_output": 0.0,
        },
    }


@pytest.fixture
def expected_processing_order() -> list[str]:
    return []


@pytest.fixture
def expected_processor_definitions_by_name() -> dict[str, dict[str, Any]]:
    return {
        "anaerobic_digester_1": {
            "name": "anaerobic_digester_1",
            "processor_type": "ContinuousMix",
            "hydraulic_retention_time": 25,
            "top_cover_volume_fraction": 0.2,
            "evaporation_fraction": 0.02,
            "temperature_set_point": 37.5,
            "methane_leakage_fraction": 0.01,
        },
        "anaerobic_digester_2": {
            "name": "anaerobic_digester_2",
            "processor_type": "ContinuousMix",
            "hydraulic_retention_time": 25,
            "top_cover_volume_fraction": 0.2,
            "evaporation_fraction": 0.02,
            "temperature_set_point": 37.5,
            "methane_leakage_fraction": 0.01,
        },
        "rotary_screen_1": {
            "name": "rotary_screen_1",
            "processor_type": "RotaryScreen",
            "separated_solids_dry_matter": 0.2,
            "total_solids_efficiency": 0.35,
            "volatile_solids_efficiency": 0.4,
            "nitrogen_efficiency": 0.3,
            "ammoniacal_nitrogen_efficiency": 0.15,
            "phosphorus_efficiency": 0.4,
            "potassium_efficiency": 0.15,
            "ash_efficiency": 0.2,
        },
        "screw_press_1": {
            "name": "screw_press_1",
            "processor_type": "ScrewPress",
            "separated_solids_dry_matter": 0.35,
            "total_solids_efficiency": 0.25,
            "volatile_solids_efficiency": 0.3,
            "nitrogen_efficiency": 0.3,
            "ammoniacal_nitrogen_efficiency": 0.1,
            "phosphorus_efficiency": 0.2,
            "potassium_efficiency": 0.23,
            "ash_efficiency": 0.2,
        },
        "slurry_storage_outdoor_1": {
            "name": "slurry_storage_outdoor_1",
            "processor_type": "SlurryStorageOutdoor",
            "capacity": None,
            "cover": "no cover",
            "storage_time_period": 120,
            "surface_area": None,
        },
        "slurry_storage_underfloor_1": {
            "name": "slurry_storage_underfloor_1",
            "processor_type": "SlurryStorageUnderfloor",
            "capacity": None,
            "cover": "cover",
            "storage_time_period": 120,
            "surface_area": None,
        },
        "anaerobic_lagoon_1": {
            "name": "anaerobic_lagoon_1",
            "processor_type": "AnaerobicLagoon",
            "capacity": None,
            "cover": "no cover",
            "storage_time_period": 365,
            "surface_area": None,
        },
        "alley_scraper_1": {
            "name": "alley_scraper_1",
            "processor_type": "AlleyScraper",
            "handler_type": "AlleyScraper",
            "cleaning_water_use_amount": 0.0,
            "cleaning_water_recycle_fraction": 0.8,
            "use_parlor_flush": False,
        },
        "manual_scraper_1": {
            "name": "manual_scraper_1",
            "processor_type": "ManualScraper",
            "handler_type": "ManualScraper",
            "cleaning_water_use_amount": 0.0,
            "cleaning_water_recycle_fraction": 0.8,
            "use_parlor_flush": False,
        },
        "flush_system_1": {
            "name": "flush_system_1",
            "processor_type": "FlushSystem",
            "handler_type": "FlushSystem",
            "cleaning_water_use_amount": 0.0,
            "cleaning_water_recycle_fraction": 0.8,
            "use_parlor_flush": False,
        },
        "parlor_cleaning_handler_1": {
            "name": "parlor_cleaning_handler_1",
            "processor_type": "ParlorCleaningHandler",
            "handler_type": "ParlorCleaningHandler",
            "cleaning_water_use_amount": 0.0,
            "cleaning_water_recycle_fraction": 0.8,
            "use_parlor_flush": True,
        },
    }


@pytest.fixture
def expected_processor_connections_by_name() -> dict[str, dict[str, list[dict[str, Any]]]]:
    return {
        "alley_scraper_1": {
            "destinations": [
                {"proportion": 0.5, "receiving_processor_name": "rotary_screen_1"},
                {"proportion": 0.5, "receiving_processor_name": "anaerobic_digester_1"},
            ]
        },
        "anaerobic_digester_1": {
            "destinations": [
                {"proportion": 0.93, "receiving_processor_name": "flush_system_1"},
                {"proportion": 0.07, "receiving_processor_name": "screw_press_1"},
            ]
        },
        "anaerobic_lagoon_1": {"destinations": []},
        "anaerobic_digester_2": {
            "destinations": [{"proportion": 1.0, "receiving_processor_name": "slurry_storage_outdoor_1"}]
        },
        "flush_system_1": {
            "destinations": [
                {"proportion": 0.1, "receiving_processor_name": "screw_press_1"},
                {"proportion": 0.8, "receiving_processor_name": "parlor_cleaning_handler_1"},
                {"proportion": 0.1, "receiving_processor_name": "slurry_storage_outdoor_1"},
            ]
        },
        "parlor_cleaning_handler_1": {
            "destinations": [
                {"proportion": 0.18, "receiving_processor_name": "anaerobic_digester_2"},
                {"proportion": 0.68, "receiving_processor_name": "anaerobic_lagoon_1"},
                {"proportion": 0.14, "receiving_processor_name": "slurry_storage_outdoor_1"},
            ]
        },
        "rotary_screen_1": {
            "liquid_output_destinations": [{"proportion": 1.0, "receiving_processor_name": "anaerobic_lagoon_1"}],
            "solid_output_destinations": [{"proportion": 1.0, "receiving_processor_name": "slurry_storage_outdoor_1"}],
        },
        "screw_press_1": {
            "liquid_output_destinations": [{"proportion": 1.0, "receiving_processor_name": "anaerobic_lagoon_1"}],
            "solid_output_destinations": [
                {"proportion": 0.2, "receiving_processor_name": "slurry_storage_outdoor_1"},
                {"proportion": 0.8, "receiving_processor_name": "anaerobic_digester_2"},
            ],
        },
        "slurry_storage_outdoor_1": {"destinations": []},
    }


@pytest.fixture
def expected_all_processor_connections() -> list[dict[str, Any]]:
    return [
        {
            "processor_name": "alley_scraper_1",
            "destinations": [
                {"receiving_processor_name": "rotary_screen_1", "proportion": 0.5},
                {"receiving_processor_name": "anaerobic_digester_1", "proportion": 0.5},
            ],
        },
        {
            "processor_name": "flush_system_1",
            "destinations": [
                {"receiving_processor_name": "screw_press_1", "proportion": 0.1},
                {"receiving_processor_name": "parlor_cleaning_handler_1", "proportion": 0.8},
                {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.1},
            ],
        },
        {
            "processor_name": "parlor_cleaning_handler_1",
            "destinations": [
                {"receiving_processor_name": "anaerobic_digester_2", "proportion": 0.18},
                {"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 0.68},
                {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.14},
            ],
        },
        {
            "processor_name": "anaerobic_digester_1",
            "destinations": [
                {"receiving_processor_name": "flush_system_1", "proportion": 0.93},
                {"receiving_processor_name": "screw_press_1", "proportion": 0.07},
            ],
        },
        {
            "processor_name": "anaerobic_digester_2",
            "destinations": [{"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 1.0}],
        },
        {"processor_name": "anaerobic_lagoon_1", "destinations": []},
        {"processor_name": "slurry_storage_outdoor_1", "destinations": []},
        {
            "processor_name": "rotary_screen_1",
            "liquid_output_destinations": [{"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 1.0}],
            "solid_output_destinations": [{"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 1.0}],
        },
        {
            "processor_name": "screw_press_1",
            "liquid_output_destinations": [{"receiving_processor_name": "anaerobic_lagoon_1", "proportion": 1.0}],
            "solid_output_destinations": [
                {"receiving_processor_name": "slurry_storage_outdoor_1", "proportion": 0.2},
                {"receiving_processor_name": "anaerobic_digester_2", "proportion": 0.8},
            ],
        },
    ]


@pytest.fixture
def expected_adjacency_matrix_keys() -> list[str]:
    return [
        "alley_scraper_1",
        "flush_system_1",
        "parlor_cleaning_handler_1",
        "anaerobic_digester_1",
        "anaerobic_digester_2",
        "anaerobic_lagoon_1",
        "slurry_storage_outdoor_1",
        "rotary_screen_1_input",
        "rotary_screen_1_solid_output",
        "rotary_screen_1_liquid_output",
        "screw_press_1_input",
        "screw_press_1_solid_output",
        "screw_press_1_liquid_output",
    ]
