from dataclasses import dataclass, field
from datetime import date

from RUFAS.general_constants import GeneralConstants
from RUFAS.rufas_time import RufasTime

"""This is the dry matter fraction above which an ensiled crop will not experience any effluent loss."""
EFFLUENT_MAXIMUM_DRY_MATTER_FRACTION = 0.3


@dataclass
class HarvestedCrop:
    """
    A class to represent a harvested crop with its attributes.

    Attributes
    ----------
    config_name : str
        Name of the crop configuration that produced this harvested crop.
    field_name : str
        Name of the field from which this crop was harvested.
    harvest_time : date
        The time at which the crop was harvested.
    storage_time : date
        The time at which the crop was stored.
    last_time_degraded : date
        The last time at which the quality and mass of the crop was recalculated. This value is initially set to the
        storage time of the crop.
    dry_matter_percentage : float
        Percent of mass that is not water.
    initial_dry_matter_percentage : float
        Percent of mass that is not water at the time this crop is stored.
    initial_dry_matter_mass : float
        Mass of dry matter initially stored (kg). Note that this value is only used if this crop is stored in a `Hay`
        instance (or one of its child classes), and is only calculated at the time of storage.
    dry_matter_digestibility : float
        Percent of mass that is digestible.
    crude_protein_percent : float
        Percent of mass that is dietary crude protein.
    non_protein_nitrogen : float
        Percent of mass that is non-protein nitrogen.
    starch : float
        Percent of mass that is starch.
    adf : float
        Percent of mass that is acid detergent fiber.
    ndf : float
        Percent of mass that is neutral detergent fiber.
    lignin : float
        Percent of mass that is lignin.
    sugar : float
        Percent of mass that is labile carbohydrate.
    ash : float
        Percent of mass that is ash.
    estimated_maximum_effluent : float
        Total amount of mass that will be lost from this crop as effluent in kg. Note that this value is only used if
        this crop is stored in a `Silage` instance (or one of its child classes), and is calculated only once, when it
        is stored.
    bale_density : float
        Density of this crop if it is hayed in kg per cubic meter. Note that this value is only used if this crop is
        stored in a `Hay` instance (or one of its child classes), and is only calculated at the time of storage.
    total_sensible_heat_generated : float
        Heat generated by this crop if it is hayed in kJ per kg. Note that this value is only used if this crop is
        stored in a `Hay` instance (or one of its child classes), and is only calculated at the time of storage.
    recorded_days : set[int]
        A set of simulation days on which this crop was recorded.
    dry_matter_mass
        The mass of dry matter in the crop in kg. This is calculated from the fresh mass and dry matter percentage.

    Methods
    -------
    __post_init__():
        Validates the category and type relationship.

    """

    config_name: str
    field_name: str
    harvest_time: date
    storage_time: date
    last_time_degraded: date = field(init=False)
    dry_matter_mass: float
    dry_matter_percentage: float
    initial_dry_matter_percentage: float = field(init=False)
    initial_dry_matter_mass: float = field(init=False)
    dry_matter_digestibility: float
    crude_protein_percent: float
    non_protein_nitrogen: float
    starch: float
    adf: float
    ndf: float
    lignin: float
    sugar: float
    ash: float
    recorded_days: set[int] = field(default_factory=set)
    estimated_maximum_effluent: float = field(init=False)
    bale_density: float = field(init=False)
    total_sensible_heat_generated: float = field(init=False)

    def __post_init__(self) -> None:
        """
        Validates that the type of the crop is consistent with its category.

        Raises
        ------
        ValueError
            If the crop type is not valid for the crop category.

        """
        self.estimated_maximum_effluent = self.estimate_maximum_effluent()
        self.bale_density = self._calculate_bale_density()
        self.total_sensible_heat_generated = self._calculate_total_sensible_heat_generated()
        self.initial_dry_matter_percentage = self.dry_matter_percentage
        self.initial_dry_matter_mass = self.dry_matter_mass
        self.last_time_degraded = self.storage_time

        if isinstance(self.harvest_time, RufasTime):
            self.harvest_time = self.harvest_time.current_date.date()
        if isinstance(self.storage_time, RufasTime):
            self.storage_time = self.storage_time.current_date.date()

    @property
    def fresh_mass(self) -> float:
        """
        Calculates the fresh matter mass of this crop in kg.
        """
        dry_matter_fraction = self.dry_matter_percentage * GeneralConstants.PERCENTAGE_TO_FRACTION
        if dry_matter_fraction == 0:
            return 0.0
        else:
            return self.dry_matter_mass / dry_matter_fraction

    @property
    def is_alfalfa(self) -> bool:
        """
        Checks if the crop is alfalfa based on its configuration name.

        Returns
        -------
        bool
            True if the crop is alfalfa, False otherwise.
        """
        return "alfalfa" in self.config_name.lower()

    def remove_dry_matter_mass(self, mass_to_remove: float) -> None:
        """
        Removes the specified dry mass of feed from the crop and keeps the dry matter percentage unchanged.

        Parameters
        ----------
        mass_to_remove : float
            Dry-matter to remove. (kg).
        """
        current_fresh_mass = self.fresh_mass

        self.dry_matter_mass -= mass_to_remove

        new_fresh_mass = current_fresh_mass - mass_to_remove

        if self.dry_matter_mass <= 0.0:
            self.dry_matter_mass = 0.0
            self.dry_matter_percentage = 0.0
            return
        self.dry_matter_percentage = (self.dry_matter_mass / new_fresh_mass) * GeneralConstants.FRACTION_TO_PERCENTAGE

    def remove_feed_mass(self, dm_to_remove: float) -> None:
        """
        Removes the specified dry matter mass of feed from the crop and keeps the dry matter percentage unchanged.

        Parameters
        ----------
        dm_to_remove : float
            Dry-matter to remove (kg).
        """
        if dm_to_remove > self.dry_matter_mass + 1e-6:
            dm_fraction = self.dry_matter_percentage * GeneralConstants.PERCENTAGE_TO_FRACTION
            fresh_required = dm_to_remove / dm_fraction if dm_fraction > 0 else 0

            raise ValueError(
                f"Cannot remove {dm_to_remove:.3f} kg DM "
                f"({fresh_required:.3f} kg fresh) - only {self.dry_matter_mass:.3f} kg dry matter available."
            )

        self.dry_matter_mass -= dm_to_remove

    def estimate_maximum_effluent(self) -> float:
        """
        Calculates the total amount of effluent loss this crop will experience if it is ensiled.

        Returns
        -------
        float
            Estimated maximum amount of mass that will flow out of this crop in kg.

        References
        ----------
        .. [1] Feed Storage Scientific Documentation, section 1.3.1

        """
        dry_matter_fraction = self.dry_matter_percentage * GeneralConstants.PERCENTAGE_TO_FRACTION
        bounded_dry_matter_fraction = min(EFFLUENT_MAXIMUM_DRY_MATTER_FRACTION, dry_matter_fraction)
        effluent_fraction = 1.0 - bounded_dry_matter_fraction - (1 - EFFLUENT_MAXIMUM_DRY_MATTER_FRACTION)
        return self.fresh_mass * effluent_fraction

    def _calculate_bale_density(self) -> float:
        """
        Calculates the bale density of hayed crop.

        Returns
        -------
        float
            Bale density of this crop (kg / cubic meter).

        References
        ----------
        .. [1] Feed Storage Scientific Documentation, equation 1.2.5

        """
        return 100 + 440 * (1.0 - self.dry_matter_percentage * GeneralConstants.PERCENTAGE_TO_FRACTION)

    def _calculate_total_sensible_heat_generated(self) -> float:
        """
        Calculates the total sensible heat generated by a hayed crop.

        Returns
        -------
        float
            Total sensible heat generated by this crop (kJ per kilogram).

        References
        ----------
        .. [1] Feed Storage Scientific Documentation, equation 1.2.4

        """
        moisture_frac = 1 - self.dry_matter_percentage * GeneralConstants.PERCENTAGE_TO_FRACTION
        heat: float = (
            104 * moisture_frac**2.18 * self.bale_density**0.5 + 5.72 * moisture_frac**1.23 * self.bale_density**0.94
        )
        return heat
